apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: platform-demo-tls
spec:
  parameters:
    clientID: "00000000-0000-0000-0000-000000000201"
    tenantId: "00000000-0000-0000-0000-000000000001"
    keyvaultName: example-platform-app
