apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-demo
resources:
  - ../../base
  - service-account.yaml
  - secret-provider-class.yaml
  - ingress.yaml
  - network-policy.yaml
  - autoscaling.yaml
patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
