apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: platform-demo-tls
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "00000000-0000-0000-0000-000000000201"
    keyvaultName: example-platform-app
    tenantId: "00000000-0000-0000-0000-000000000001"
    objects: |
      array:
        - |
          objectName: platform-demo-ingress
          objectType: secret
          objectFormat: pem
          objectVersion: ""
  secretObjects:
    - secretName: platform-demo-tls
      type: kubernetes.io/tls
      data:
        - objectName: platform-demo-ingress
          key: tls.key
        - objectName: platform-demo-ingress
          key: tls.crt
